### ISSUE TITLE
(Feature Request) Allow user to specify how style attribute is computed

### ISSUE THREAD

**Issue by tomconnors** [TheNaschkatze/tiptap-extension-font-size#11]
I have an admittedly uncommon use case of needing to scale the font, so I forked this library and made this minor change:
``` javascript
// (in addGlobalAttributes)
return {
    style: `font-size: calc(var(--font-scale) * ${attributes.fontSize})`
};
```

I wouldn't have needed to fork the library if it exposed an option that would allow the user to provide a function to calculate the value for the style attribute, in which case that line would look more like:
``` javascript
return {
    style: this.options.getStyle()
};
```

Seems like an easy enough change, and the current behavior could be the default.

**Comment by TheNaschkatze** [comment]
@tomconnors Do you want to open a pr?
