### ISSUE TITLE
JS Build Broken

### ISSUE THREAD

**Issue by catrielmuller** [TheNaschkatze/tiptap-extension-font-size#6]
Hey @TheNaschkatze , the last release was not builded in JavaScript

Can you release a new version like 1.2.3  using the github action that I created or directly on your end with this commands

```
npm install
npm run build
npm publish --access public
```

**Comment by TheNaschkatze** [comment]
sure do!

I wish GitHub had a chat tho xD

**Comment by catrielmuller** [comment]
Thanks, worked perfect now
