### ISSUE TITLE
[tiptap warn]: BREAKING CHANGE: "defaultOptions" is deprecated.

### ISSUE THREAD

**Issue by tobychidi-zz** [TheNaschkatze/tiptap-extension-font-size#7]
Tiptap is throwing a warning

[tiptap warn]: BREAKING CHANGE: "defaultOptions" is deprecated. Please use "addOptions" instead. Found in extension: "fontSize".

**Comment by TheNaschkatze** [comment]
Hi, @tobychidi ✋🏼 I just published a very similar version of your pr, would you mind update?

thanks :)

**Comment by tobychidi-zz** [comment]
@TheNaschkatze Awesome! Thank you 👏
